import Head from 'next/head'
import Footer from '../components/footer'
import Hero from '../components/hero'
import Navbar from '../components/nav'
import Section2 from '../components/section2'
import Section3 from '../components/section3'
import Section4 from '../components/section4'
import Section5 from '../components/section5'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Hero/>
    
    <Section2/>
    <Section3/>
    <Section4/>
    <Section5/>

    <Footer/>

    </>
  )
}
